// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv5XPrFeLha82Jr_R7VdFmcNzUQ3qubTs',
    appId: '1:341601045251:web:16142f11c387e190e43736',
    messagingSenderId: '341601045251',
    projectId: 'kopicue-188a2',
    authDomain: 'kopicue-188a2.firebaseapp.com',
    storageBucket: 'kopicue-188a2.firebasestorage.app',
    measurementId: 'G-P0YQBS5MR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXoHNIppxMJyopMxicxg0j0jPLMYsMl8',
    appId: '1:341601045251:android:acda2e703be84ab8e43736',
    messagingSenderId: '341601045251',
    projectId: 'kopicue-188a2',
    storageBucket: 'kopicue-188a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcnnRnxUbIj6x14Gc3X4JytInV_-YsBKU',
    appId: '1:341601045251:ios:d4b3bde0c693d4bfe43736',
    messagingSenderId: '341601045251',
    projectId: 'kopicue-188a2',
    storageBucket: 'kopicue-188a2.firebasestorage.app',
    iosBundleId: 'com.example.kopicue',
  );
}
